In [1]:
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm
import os.path
from scipy import stats
import random
import PIL.ImageDraw as ImageDraw
import PIL.Image as Image
import math





In [10]:
def load_images():
    img_path = './imgs/'
    imgs = []
    for file in tqdm(os.listdir(img_path)):
        imgs.append(np.array(Image.open(img_path + file)))
    return imgs

In [11]:
img = load_images()[0]

100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.56it/s]


In [12]:
def generate_histogram(img):
    """
    @params: img: can be a grayscale or color image. We calculate the Normalized histogram of this image.
    @params: do_print: if or not print the result histogram
    @return: will return both histogram and the grayscale image 
    """
    if len(img.shape) == 3: # img is colorful, so we convert it to grayscale
        gr_img = np.mean(img, axis=-1)
    else:
        gr_img = img
    '''now we calc grayscale histogram'''
    gr_hist = np.zeros([256])

    for x_pixel in range(gr_img.shape[0]):
        for y_pixel in range(gr_img.shape[1]):
            pixel_value = int(gr_img[x_pixel, y_pixel])
            gr_hist[pixel_value] += 1
            
    '''normalizing the Histogram'''
    ##gr_hist /= (gr_img.shape[0] * gr_img.shape[1])
    return gr_hist, gr_img

In [13]:
len(generate_histogram(img)[0])

256

In [6]:
pixel_count1 = generate_histogram(img)[0]

In [7]:
intensity = list(range(0,256))

In [8]:
import pandas as pd

In [18]:
pd.DataFrame(pixel_count1, columns = ['pixel_count1'])

pixel_count1
0            75.0
1             0.0
2            53.0
3            61.0
4            82.0
..            ...
251           0.0
252           0.0
253           0.0
254           0.0
255           0.0

[256 rows x 1 columns]

In [14]:
pixel_count2 = generate_histogram(img)[0]

In [15]:
pixel_count2

array([4.0000e+00, 8.0000e+00, 9.0000e+00, 1.2000e+01, 2.5000e+01,
       3.1000e+01, 5.6000e+01, 5.4000e+01, 7.0000e+01, 9.5000e+01,
       9.0000e+01, 1.0000e+02, 1.3700e+02, 1.4400e+02, 1.4000e+02,
       1.3600e+02, 1.3400e+02, 1.1600e+02, 1.4100e+02, 1.0000e+02,
       1.2700e+02, 1.3400e+02, 1.3800e+02, 1.3300e+02, 1.5000e+02,
       1.6200e+02, 1.3400e+02, 1.4700e+02, 1.2500e+02, 1.8600e+02,
       1.7300e+02, 1.7000e+02, 1.7500e+02, 1.7500e+02, 1.5900e+02,
       1.7500e+02, 1.7700e+02, 1.7000e+02, 1.8300e+02, 2.1500e+02,
       2.3100e+02, 2.4000e+02, 2.2000e+02, 2.2500e+02, 2.3100e+02,
       2.3600e+02, 2.5700e+02, 2.3500e+02, 2.8000e+02, 2.7100e+02,
       2.5000e+02, 2.7800e+02, 2.5800e+02, 2.7400e+02, 2.8000e+02,
       2.6000e+02, 2.6700e+02, 3.1500e+02, 3.0400e+02, 3.5900e+02,
       3.7500e+02, 3.2200e+02, 3.5300e+02, 3.5800e+02, 3.8000e+02,
       3.7900e+02, 4.2800e+02, 4.3000e+02, 4.6000e+02, 5.2500e+02,
       5.1300e+02, 5.5200e+02, 5.9000e+02, 6.4100e+02, 6.5500e

In [16]:
pd.DataFrame(pixel_count2, columns = ['pixel_count2'])

pixel_count2
0             4.0
1             8.0
2             9.0
3            12.0
4            25.0
..            ...
251           0.0
252           0.0
253           0.0
254           0.0
255           0.0

[256 rows x 1 columns]

In [17]:
pixel_count1

array([7.500e+01, 0.000e+00, 5.300e+01, 6.100e+01, 8.200e+01, 7.700e+01,
       4.200e+01, 5.900e+01, 7.700e+01, 9.200e+01, 2.260e+02, 9.400e+01,
       1.450e+02, 2.060e+02, 2.050e+02, 4.110e+02, 5.250e+02, 4.970e+02,
       7.160e+02, 7.300e+02, 8.970e+02, 7.440e+02, 7.320e+02, 8.220e+02,
       8.710e+02, 8.170e+02, 7.550e+02, 9.890e+02, 1.147e+03, 1.112e+03,
       1.024e+03, 1.115e+03, 1.084e+03, 1.283e+03, 1.361e+03, 1.195e+03,
       1.272e+03, 1.208e+03, 1.328e+03, 1.518e+03, 1.610e+03, 1.487e+03,
       1.198e+03, 1.354e+03, 1.348e+03, 1.397e+03, 1.323e+03, 1.445e+03,
       1.405e+03, 1.484e+03, 1.373e+03, 1.309e+03, 1.377e+03, 1.392e+03,
       1.195e+03, 1.170e+03, 1.090e+03, 1.253e+03, 1.327e+03, 1.321e+03,
       1.263e+03, 1.226e+03, 1.316e+03, 1.562e+03, 1.477e+03, 1.734e+03,
       1.611e+03, 1.622e+03, 1.787e+03, 1.834e+03, 1.796e+03, 1.974e+03,
       1.828e+03, 1.986e+03, 2.138e+03, 2.055e+03, 2.118e+03, 2.113e+03,
       2.158e+03, 2.031e+03, 2.087e+03, 2.012e+03, 

In [ ]:
generate_histogram(img)

In [19]:
r = np.corrcoef(pixel_count1, pixel_count2)

In [20]:
r

array([[ 1.        , -0.07814372],
       [-0.07814372,  1.        ]])